accounts/urls.py
from django.urls import path
from .views import SettingsPageView
from accounts import views as user_views

urlpatterns = [
    path('settings/', SettingsPageView.as_view(), name='settings')
]

hasker_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from questions import views
from django.conf import settings
from django.conf.urls.static import static

from questions.views import SearchResultsListView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # Local apps
                  path('', include('questions.urls', namespace='questions')),
                  path('search/', SearchResultsListView.as_view(),
                       name='search_results'),
                  # path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/', include('allauth.urls')),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

questions/urls.py
from django.urls import path
from . import views
from .views import QuestionListView, QuestionDetailView, QuestionCreateView, QuestionUpdateView, QuestionDeleteView, \
    tagged, question_vote, answer_vote, AnswerUpdateView, AnswerDeleteView, SearchResultsListView, answer_right, \
    answer_create

app_name = "questions"

urlpatterns = [
    path(r'', QuestionListView.as_view(), name='question_list'),
    path('create_question/', QuestionCreateView.as_view(), name="create_question"),
    path('question_detail/<uuid:pk>/', QuestionDetailView.as_view(), name='question_detail'),
    path('question_update/<uuid:pk>/', QuestionUpdateView.as_view(), name="question_update"),
    path('question_delete/<uuid:pk>/', QuestionDeleteView.as_view(), name="question_delete"),
    path('create_answer/', answer_create, name='create_answer'),
    path('question_tag/<slug:slug>/', tagged, name="tagged"),
    path('question_vote/', question_vote, name="question_vote"),
    path('answer_vote/', answer_vote, name="answer_vote"),
    path('answer_right/', answer_right, name="answer_right"),
    path('answer_update/<uuid:pk>/', AnswerUpdateView.as_view(), name="answer_update"),
    path('answer_delete/<uuid:pk>/', AnswerDeleteView.as_view(), name="answer_delete"),


]

questions/models.py
import uuid
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import ArrayField

from taggit.managers import TaggableManager
from taggit.models import GenericUUIDTaggedItemBase, TaggedItemBase, TagBase, Tag
from django.utils.translation import ugettext_lazy as _, pgettext_lazy

# Create your models here.
from unidecode import unidecode


class Tags(Tag):
    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")

    def slugify(self, tag, i=None):
        slug = slugify(unidecode(tag))
        if i is not None:
            slug += "_%d" % i
        return slug


class UUIDTaggedItem(GenericUUIDTaggedItemBase, TaggedItemBase):
    # If you only inherit GenericUUIDTaggedItemBase, you need to define
    # a tag field. e.g.
    tag = models.ForeignKey(Tags, related_name="uuid_tagged_items", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")


class Question(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="question_author")
    title = models.CharField(max_length=255, default="", null=True)
    text = models.TextField()
    voted = models.ManyToManyField(get_user_model(), default=None, blank=True, related_name="voted_question")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = TaggableManager(through=UUIDTaggedItem)

    class Meta:
        ordering = ["-created_at"]

    #
    # def was_updated_recently(self):
    #     return timezone.now() - self.updated_at

    def __str__(self):
        return str(self.title)

    @property
    def num_votes(self):
        return self.voted.all().count()

    def get_absolute_url(self):
        return reverse('questions:question_detail', args=[str(self.id)])


class Answer(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name='answer',
    )
    answer_text = models.TextField()
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="answer_author")
    voted = models.ManyToManyField(get_user_model(), default=None, blank=True, related_name="voted_answer")
    created_at = models.DateTimeField(auto_now_add=True)
    right_flag = models.BooleanField(default=False)

    def __str__(self):
        return str(self.answer_text)

    @property
    def num_votes(self):
        return self.voted.all().count()

    class Meta:
        ordering = ["-created_at"]


VOTE_CHOICES = (
    ('Poll', 'Poll'),
    ('Unpoll', 'Unpoll')
)


class VoteQuestion(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    vote_date = models.DateTimeField(auto_now_add=True)
    polled = models.CharField(choices=VOTE_CHOICES, default='poll', max_length=10)

    class Meta:
        ordering = ["-vote_date"]

    def was_votes_recently(self):
        return timezone.now() - self.vote_date

    def __str__(self):
        return str(self.question)


class VoteAnswer(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    vote_date = models.DateTimeField(auto_now_add=True)
    polled = models.CharField(choices=VOTE_CHOICES, default='poll', max_length=10)

    class Meta:
        ordering = ["-vote_date"]

    def __str__(self):
        return str(self.answer)

questions/forms.py
from django import forms

from . import models


class QuestionForm(forms.ModelForm):
    class Meta:
        model = models.Question
        fields = [
          'title', 'text', 'tags',
        ]


class AnswerForm(forms.ModelForm):
    right_flag = forms.BooleanField(required=False)

    class Meta:
        model = models.Answer
        fields = [
            'right_flag'
        ]

questions/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, Count
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, TemplateView
from django.core.paginator import Paginator
from taggit.models import Tag
from django.core.mail import send_mail

from accounts.models import CustomUser
from hasker_Project import settings
from .forms import QuestionForm, AnswerForm
from .models import Question, Answer, VoteAnswer, VoteQuestion


class QuestionListView(ListView):
    model = Question
    template_name = 'questions/question_list.html'
    context_object_name = 'question_list'
    queryset = Question.objects.all(). \
        annotate(consumption_times=Count('voted')).order_by('-consumption_times', '-created_at')


class QuestionActionMixin:
    form_class = QuestionForm

    @property
    def success_msg(self):
        return NotImplemented

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.info(self.request, self.success_msg)
        return super().form_valid(form)


class QuestionCreateView(LoginRequiredMixin, QuestionActionMixin, CreateView):
    template_name = 'questions/question_form.html'
    common_tags = Question.tags.most_common()[:3]
    models = Question
    success_msg = "Question created!"
    action = "Add"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = self.request.user
        context['common_tags'] = self.common_tags
        context['question_list'] = Question.objects.all(). \
            annotate(consumption_times=Count('voted')).order_by('-consumption_times', '-created_at')
        return context


class QuestionDetailView(LoginRequiredMixin, DetailView):
    model = Question
    template_name = 'questions/question_detail.html'
    context_object_name = 'question'

    def get_context_data(self, **kwargs):
        form = AnswerForm
        context = super().get_context_data(**kwargs)
        answers_list = Answer.objects.filter(question_id=self.kwargs.get("pk")) \
            .annotate(consumption_times=Count('voted')).order_by('-consumption_times', '-created_at')
        righ_flag = Answer.objects.filter(question_id=self.kwargs.get("pk"), right_flag=True).count()
        paginator = Paginator(answers_list, 30)
        page = self.request.GET.get('page')
        answers = paginator.get_page(page)
        context['answers'] = answers
        context['question_list'] = Question.objects.all(). \
            annotate(consumption_times=Count('voted')).order_by('-consumption_times', '-created_at')
        context['form'] = form
        return context


class QuestionUpdateView(LoginRequiredMixin, UpdateView):
    model = Question
    template_name = 'questions/question_form.html'
    action = "Update"
    context_object_name = 'question_update'
    common_tags = Question.tags.most_common()[:3]
    fields = [
        'author',
        'title',
        'text',
        'tags',
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['common_tags'] = self.common_tags
        context['question_list'] = Question.objects.all(). \
            annotate(consumption_times=Count('voted')).order_by('-consumption_times', '-created_at')
        return context


class QuestionDeleteView(LoginRequiredMixin, DeleteView):
    model = Question
    success_url = reverse_lazy('questions:question_list')
    action = "Delete"


class AnswerUpdateView(LoginRequiredMixin, UpdateView):
    model = Answer
    template_name = 'questions/answer_form.html'
    success_url = reverse_lazy('questions:question_list')
    action = "Update"
    context_object_name = 'answer_update'
    fields = [
        'answer_text'
    ]


class AnswerDeleteView(LoginRequiredMixin, DeleteView):
    model = Answer
    success_url = reverse_lazy('questions:question_list')
    action = "Delete"


def answer_create(request):
    user = request.user
    if request.method == "POST":
        answer_text = request.POST.get('answer_text')
        question_id = request.POST.get('question_id')
        questions_list = Question.objects.get(id=question_id)
        customuser = CustomUser.objects.get(email=questions_list.author)
        email = questions_list.author
        login = customuser.login
        _answer, created = Answer.objects.get_or_create(question=questions_list, answer_text=answer_text, author=user)
        _answer.save()
        send_mail('Hasker. New answer', "Hello "
                  + login + " you have new answer for your question with title: "
                  + questions_list.title, settings.DEFAULT_FROM_EMAIL, [email])
    return redirect('questions:question_list')


def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    # Filter posts by tag name
    questions_list = Question.objects.filter(tags=tag)
    context = {
        'tag': tag,
        'questions_list': questions_list,
    }
    return render(request, 'questions/question_list.html', context)


def question_vote(request):
    user = request.user
    if request.method == "POST":
        question_id = request.POST.get('question_id')
        questions_list = Question.objects.get(id=question_id)
        if 'vote' in request.POST.keys():
            questions_list.voted.add(user)
        if 'unvote' in request.POST.keys():
            questions_list.voted.remove(user)
        vote, created = VoteQuestion.objects.get_or_create(user=user, question_id=question_id)
        if not created:
            if vote.polled == 'Poll':
                vote.polled = 'Unpoll'
            else:
                vote.polled = 'Poll'
        vote.save()
    return redirect('questions:question_list')


def answer_vote(request):
    user = request.user
    if request.method == "POST":
        answer_id = request.POST.get('answer_id')
        question_id = request.POST.get('question_id')
        answer_list = Answer.objects.get(id=answer_id)
        if 'answer_vote' in request.POST.keys():
            answer_list.voted.add(user)
        if 'answer_unvote' in request.POST.keys():
            answer_list.voted.remove(user)
        vote, created = VoteAnswer.objects.get_or_create(user=user, answer_id=answer_id)
        if not created:
            if vote.polled == 'Poll':
                vote.polled = 'Unpoll'
            else:
                vote.polled = 'Poll'
        vote.save()
    return redirect('questions:question_detail', question_id)


def answer_right(request):
    if request.method == "POST":
        answer_id = request.POST.get('answer_id')
        question_id = request.POST.get('question_id')
        right_flag = True if request.POST.get('right_flag') == 'on' else False
        answer = Answer.objects.get(id=answer_id)
        answer.right_flag = right_flag
        answer.save()
    return redirect('questions:question_detail', question_id)


class SearchResultsListView(ListView):
    model = Question
    context_object_name = 'question_list'
    template_name = 'questions/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        return Question.objects.filter(
            Q(title__icontains=query)
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        answers = Answer.objects.all()
        context['answers'] = answers
        return context

templates/questions/answer_confirm_delete.html
{% extends "_base.html" %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %}
Confirm removing answer.
{% endblock title %}
{% block content %}
    {{ block.super }}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

templates/questions/answer_form.html
{% extends "_base.html" %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %}
    {#    {{ form.instance.title | default:"New Question" }} | {{ question.title }} {{ block.super }}#}
    {{ view.action|default:"Update" }} Answer
{% endblock title %}

{% block content %}
    {{ block.super }}
    <div class="col-sm-9 col-md-7 col-lg-9 mx-auto">
        <div class="card card-signin my-5 border-info flex-row">
            <div class="card-body">
                {% with action=view.action|default:"Update" %}
                    <h2 class="card-title text-center text-info">
                        {{ action }} answer</h2>
                    {% if user.is_authenticated %}
                        <form method="POST" action=".">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.answer_text | as_crispy_field }}
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    {% endif %}
                {% endwith %}
            </div>
        </div>
    </div>

{% endblock content %}

templates/questions/question_detail.html
{% extends "_base.html" %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block title %}
    {#    {{ form.instance.title | default:"New Question" }} | {{ question.title }} {{ block.super }}#}
    {{ question.title }}
{% endblock title %}

{% block content %}
    {{ block.super }}
    <br>
    <div class="card" style="width: 36rem;">
        <div class="row g-0 ">
            <div class="col-md-4">
                <div class="container h-100 border bg-light">
                    <form class="p-3" action="{% url 'questions:question_vote' %}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col text-center">
                                <input type="hidden" name="question_id" value="{{ question.pk }}">
                                <button class="btn" type="submit" name="vote">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30"
                                         fill="currentColor"
                                         class="bi bi-caret-up-fill" viewBox="2 0 15 15">
                                        <path d="m7.247 4.86-4.796 5.481c-.566.647-.106 1.659.753 1.659h9.592a1 1 0
                                            0 0 .753-1.659l-4.796-5.48a1 1 0 0 0-1.506 0z"/>
                                    </svg>
                                </button>
                            </div>
                        </div>
                        <div class="row ">
                            <div class="col text-center">
                                <h3>
                                    <strong>{{ question.voted.all.count }}</strong>
                                </h3>
                            </div>
                        </div>
                        <div class="row text-center">
                            <div class="col text-center">
                                <button class="btn" type="submit" name="unvote">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30"
                                         fill="currentColor"
                                         class="bi bi-caret-down-fill" viewBox="2 0 15 15">
                                        <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1
                                            1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
                                    </svg>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ question.title }}
                    </h5>
                    <p class="card-text">
                        {{ question.text }}
                    </p>
                    <p class="card-text">
                        {% for tag in question.tags.all %}
                            <a href="{% url 'questions:tagged' tag.slug %}"
                               class="mr-1 badge badge-info">#{{ tag }}</a>
                        {% endfor %}
                    </p>
                    {% if user == question.author %}
                        <a class="btn btn-primary"
                           href="{% url 'questions:question_update' pk=question.pk %}">Update Question</a>
                        <a class="btn btn-primary"
                           href="{% url 'questions:question_delete' pk=question.pk %}">Delete Question</a>
                    {% endif %}
                    <p class="card-text">
                        <img class="img-thumbnail" src="{{ question.author.avatar.url }}"
                             alt="{{ question.author.login }}"> {{ question.author.login }}
                    </p>
                </div>
            </div>
        </div>
    </div>

    </br>
    <strong>Answers:</strong>
    <div class="card" style="width: 38rem;">
        {% for item in answers %}
            <p></p>
            <div class="card m-3" style="width: 36rem;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <div class="container h-100 border bg-light">
                            <form action="{% url 'questions:answer_vote' %}" method="POST">
                                <div class="row">
                                    <div class="col text-center">
                                        {% csrf_token %}
                                        <input type="hidden" name="answer_id" value="{{ item.id }}">
                                        <input type="hidden" name="question_id" value="{{ question.pk }}">
                                        <button class="btn" type="submit" name="answer_vote">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30"
                                                 fill="currentColor"
                                                 class="bi bi-caret-up-fill" viewBox="0 0 15 15">
                                                <path d="m7.247 4.86-4.796 5.481c-.566.647-.106 1.659.753 1.659h9.592a1 1 0
                                            0 0 .753-1.659l-4.796-5.48a1 1 0 0 0-1.506 0z"/>
                                            </svg>
                                        </button>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col text-center">
                                        <h3>
                                            <strong>{{ item.voted.all.count }}</strong>
                                        </h3>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col text-center">
                                        <button class="btn" type="submit" name="answer_unvote">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30"
                                                 fill="currentColor"
                                                 class="bi bi-caret-down-fill" viewBox="0 0 15 15">
                                                <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1
                                            1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
                                            </svg>
                                        </button>
                                    </div>
                                </div>
                            </form>
                            <div class="row">
                                <div class="col text-center">
                                    <form action="{% url 'questions:answer_right' %}" method="post">
                                        {% csrf_token %}
                                        {% if user.is_authenticated %}
                                            {% if user == question.author and right_flag == 0 %}
                                                <div class="form-check">
                                                    {{ form.right_flag | as_crispy_field }}
                                                    <input type="hidden" name="answer_id" value="{{ item.id }}">
                                                    <input type="hidden" name="question_id" value="{{ question.pk }}">
                                                    <button type="submit" class="btn btn-primary">Submit</button>
                                                </div>
                                            {% endif %}
                                        {% endif %}
                                    </form>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col text-center">
                                    {% if item.right_flag %}
                                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="Blue"
                                             class="bi bi-award-fill" viewBox="0 0 16 16">
                                            <path style="fill: green" d="m8 0 1.669.864 1.858.282.842 1.68 1.337 1.32L13.4
                                        6l.306 1.854-1.337 1.32-.842 1.68-1.858.282L8
                                        12l-1.669-.864-1.858-.282-.842-1.68-1.337-1.32L2.6 6l-.306-1.854
                                        1.337-1.32.842-1.68L6.331.864 8 0z"/>
                                            <path style="fill: green" d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8
                                        13.126 6.018 12.1 4 11.794z"/>
                                        </svg>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <p class="card-text">
                                {{ item.answer_text }}
                            </p>
                            <p class="card-text"><small class="text-muted">{{ item.created_at }}</small></p>
                            {% if user == item.author %}
                                <a class="btn btn-primary"
                                   href="{% url 'questions:answer_update' pk=item.pk %}">Update Answer</a>
                                <a class="btn btn-primary"
                                   href="{% url 'questions:answer_delete' pk=item.pk %}">Delete Answer</a>
                            {% endif %}
                            {% if user.is_authenticated %}
                                <p class="card-text">
                                    <img class="img-thumbnail" src="{{ item.author.avatar.url }}"
                                         alt="{{ item.author.login }}"> {{ item.author.login }}
                                </p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <nav aria-label="Page navigation example">
        <ul class="pagination">

            {% if answers.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ answers.previous_page_number }}">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Previous</a>
                </li>
            {% endif %}
            {% for page in answers.paginator.page_range %}
                {% if page == answers.number %}
                    <li class="page-item active"><a class="page-link" href="?page={{ page }}">{{ page }}</a>
                        {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a>
                {% endif %}
            {% endfor %}
            <li class="page-item">
                {% if answers.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ answers.next_page_number }}">Next</a>
                    </li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link">Next</a></li>
                {% endif %}
            </li>
        </ul>
    </nav>
    {% if user.is_authenticated %}
        <form method="POST" action="{% url 'questions:create_answer' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="answer_text" class="form-label">Answer</label>
                <input type="hidden" name="question_id" value="{{ question.id }}">
                <textarea class="form-control" name="answer_text" id="answer_text"
                          rows="3">
                </textarea>
                <button type="submit" class="btn btn-primary">Answer!</button>
            </div>
        </form>
    {% endif %}
{% endblock content %}

templates/questions/question_list.html
{% extends '_base.html' %}
{% block title %}Questions{% endblock title %}
{% block content %}
    {{ block.super }}
    {% for q in question_list %}
        <div class="card mb-3" style="width: 36rem;">
            <div class="row g-0">
                <div class="col-md-4">
                    <div class="h-100 w-50 border bg-light">
                        <form class="p-3 " action="{% url 'questions:question_vote' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="question_id" value="{{ q.id }}">
                            <button class="btn" type="submit" name="vote">
                                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                                     class="bi bi-caret-up-fill" viewBox="2 0 15 15">
                                    <path d="m7.247 4.86-4.796 5.481c-.566.647-.106 1.659.753 1.659h9.592a1 1 0
                                0 0 .753-1.659l-4.796-5.48a1 1 0 0 0-1.506 0z"/>
                                </svg>
                            </button>
                            <h3 class="text-center">
                                <strong>{{ q.voted.all.count }}</strong>
                            </h3>
                            <button class="btn" type="submit" name="unvote">
                                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                                     class="bi bi-caret-down-fill" viewBox="2 0 15 15">
                                    <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1
                                1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
                                </svg>
                            </button>
                        </form>
                    </div>
                </div>
                <div class="col-md-8">
                    <p class="card-body">

                    <h5 class="card-title">
                        <a href="{{ q.get_absolute_url }}">{{ q.title }}</a>
                    </h5>
                    <p class="card-text">
                        {{ q.text | truncatewords:"20" }}
                    </p>
                    <p class="card-text"><small class="text-muted">{{ q.created_at }}</small></p>

                    <p class="card-text">
                        {% for tag in q.tags.all %}
                            <a href="{% url 'questions:tagged' tag.slug %}"
                               class="mr-1 badge badge-info">#{{ tag }}</a>
                        {% endfor %}
                        <img class="img-thumbnail" src="{{ q.author.avatar.url }}"
                             alt="{{ q.author.login }}">{{ q.author.login }}
                    </p>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}