accounts/urls.py
from django.urls import path
from .views import SettingsPageView
from accounts import views as user_views

urlpatterns = [
    path('settings/', SettingsPageView.as_view(), name='settings')
]

hasker_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from questions import views
from django.conf import settings
from django.conf.urls.static import static

from questions.views import SearchResultsListView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # Local apps
                  path('', include('questions.urls', namespace='questions')),
                  path('search/', SearchResultsListView.as_view(),
                       name='search_results'),
                  # path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/', include('allauth.urls')),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

questions/urls.py
from django.urls import path
from . import views
from .views import QuestionListView, QuestionDetailView, QuestionCreateView, QuestionUpdateView, QuestionDeleteView, \
    tagged, question_vote, answer_vote, AnswerUpdateView, AnswerDeleteView, SearchResultsListView, answer_right, \
    answer_create

app_name = "questions"

urlpatterns = [
    path(r'', QuestionListView.as_view(), name='question_list'),
    path('create_question/', QuestionCreateView.as_view(), name="create_question"),
    path('question_detail/<uuid:pk>/', QuestionDetailView.as_view(), name='question_detail'),
    path('question_update/<uuid:pk>/', QuestionUpdateView.as_view(), name="question_update"),
    path('question_delete/<uuid:pk>/', QuestionDeleteView.as_view(), name="question_delete"),
    path('create_answer/', answer_create, name='create_answer'),
    path('question_tag/<slug:slug>/', tagged, name="tagged"),
    path('question_vote/', question_vote, name="question_vote"),
    path('answer_vote/', answer_vote, name="answer_vote"),
    path('answer_right/', answer_right, name="answer_right"),
    path('answer_update/<uuid:pk>/', AnswerUpdateView.as_view(), name="answer_update"),
    path('answer_delete/<uuid:pk>/', AnswerDeleteView.as_view(), name="answer_delete"),


]

questions/models.py
import uuid
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import ArrayField

from taggit.managers import TaggableManager
from taggit.models import GenericUUIDTaggedItemBase, TaggedItemBase, TagBase, Tag
from django.utils.translation import ugettext_lazy as _, pgettext_lazy

# Create your models here.
from unidecode import unidecode


class Tags(Tag):
    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")

    def slugify(self, tag, i=None):
        slug = slugify(unidecode(tag))
        if i is not None:
            slug += "_%d" % i
        return slug


class UUIDTaggedItem(GenericUUIDTaggedItemBase, TaggedItemBase):
    # If you only inherit GenericUUIDTaggedItemBase, you need to define
    # a tag field. e.g.
    tag = models.ForeignKey(Tags, related_name="uuid_tagged_items", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")


class Question(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="question_author")
    title = models.CharField(max_length=255, default="", null=True)
    text = models.TextField()
    voted = models.ManyToManyField(get_user_model(), default=None, blank=True, related_name="voted_question")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = TaggableManager(through=UUIDTaggedItem)

    class Meta:
        ordering = ["-created_at"]

    #
    # def was_updated_recently(self):
    #     return timezone.now() - self.updated_at

    def __str__(self):
        return str(self.title)

    @property
    def num_votes(self):
        return self.voted.all().count()

    def get_absolute_url(self):
        return reverse('questions:question_detail', args=[str(self.id)])


class Answer(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name='answer',
    )
    answer_text = models.TextField()
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="answer_author")
    voted = models.ManyToManyField(get_user_model(), default=None, blank=True, related_name="voted_answer")
    created_at = models.DateTimeField(auto_now_add=True)
    right_flag = models.BooleanField(default=False)

    def __str__(self):
        return str(self.answer_text)

    @property
    def num_votes(self):
        return self.voted.all().count()

    class Meta:
        ordering = ["-created_at"]


VOTE_CHOICES = (
    ('Poll', 'Poll'),
    ('Unpoll', 'Unpoll')
)


class VoteQuestion(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    vote_date = models.DateTimeField(auto_now_add=True)
    polled = models.CharField(choices=VOTE_CHOICES, default='poll', max_length=10)

    class Meta:
        ordering = ["-vote_date"]

    def was_votes_recently(self):
        return timezone.now() - self.vote_date

    def __str__(self):
        return str(self.question)


class VoteAnswer(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    vote_date = models.DateTimeField(auto_now_add=True)
    polled = models.CharField(choices=VOTE_CHOICES, default='poll', max_length=10)

    class Meta:
        ordering = ["-vote_date"]

    def __str__(self):
        return str(self.answer)

questions/forms.py
from django import forms

from . import models


class QuestionForm(forms.ModelForm):
    class Meta:
        model = models.Question
        fields = [
          'title', 'text', 'tags',
        ]


class AnswerForm(forms.ModelForm):
    right_flag = forms.BooleanField(required=False)

    class Meta:
        model = models.Answer
        fields = [
            'right_flag'
        ]

questions/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, Count
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, TemplateView
from django.core.paginator import Paginator
from taggit.models import Tag
from django.core.mail import send_mail

from accounts.models import CustomUser
from hasker_Project import settings
from .forms import QuestionForm, AnswerForm
from .models import Question, Answer, VoteAnswer, VoteQuestion


class QuestionListView(ListView):
    model = Question
    template_name = 'questions/question_list.html'
    context_object_name = 'question_list'
    queryset = Question.objects.all(). \
        annotate(consumption_times=Count('voted')).order_by('-consumption_times', '-created_at')


class QuestionActionMixin:
    form_class = QuestionForm

    @property
    def success_msg(self):
        return NotImplemented

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.info(self.request, self.success_msg)
        return super().form_valid(form)


class QuestionCreateView(LoginRequiredMixin, QuestionActionMixin, CreateView):
    template_name = 'questions/question_form.html'
    common_tags = Question.tags.most_common()[:3]
    models = Question
    success_msg = "Question created!"
    action = "Add"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = self.request.user
        context['common_tags'] = self.common_tags
        context['question_list'] = Question.objects.all(). \
            annotate(consumption_times=Count('voted')).order_by('-consumption_times', '-created_at')
        return context


class QuestionDetailView(LoginRequiredMixin, DetailView):
    model = Question
    template_name = 'questions/question_detail.html'
    context_object_name = 'question'

    def get_context_data(self, **kwargs):
        form = AnswerForm
        context = super().get_context_data(**kwargs)
        answers_list = Answer.objects.filter(question_id=self.kwargs.get("pk")) \
            .annotate(consumption_times=Count('voted')).order_by('-consumption_times', '-created_at')
        righ_flag = Answer.objects.filter(question_id=self.kwargs.get("pk"), right_flag=True).count()
        paginator = Paginator(answers_list, 30)
        page = self.request.GET.get('page')
        answers = paginator.get_page(page)
        context['answers'] = answers
        context['question_list'] = Question.objects.all(). \
            annotate(consumption_times=Count('voted')).order_by('-consumption_times', '-created_at')
        context['form'] = form
        return context


class QuestionUpdateView(LoginRequiredMixin, UpdateView):
    model = Question
    template_name = 'questions/question_form.html'
    action = "Update"
    context_object_name = 'question_update'
    common_tags = Question.tags.most_common()[:3]
    fields = [
        'author',
        'title',
        'text',
        'tags',
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['common_tags'] = self.common_tags
        context['question_list'] = Question.objects.all(). \
            annotate(consumption_times=Count('voted')).order_by('-consumption_times', '-created_at')
        return context


class QuestionDeleteView(LoginRequiredMixin, DeleteView):
    model = Question
    success_url = reverse_lazy('questions:question_list')
    action = "Delete"


class AnswerUpdateView(LoginRequiredMixin, UpdateView):
    model = Answer
    template_name = 'questions/answer_form.html'
    success_url = reverse_lazy('questions:question_list')
    action = "Update"
    context_object_name = 'answer_update'
    fields = [
        'answer_text'
    ]


class AnswerDeleteView(LoginRequiredMixin, DeleteView):
    model = Answer
    success_url = reverse_lazy('questions:question_list')
    action = "Delete"


def answer_create(request):
    user = request.user
    if request.method == "POST":
        answer_text = request.POST.get('answer_text')
        question_id = request.POST.get('question_id')
        questions_list = Question.objects.get(id=question_id)
        customuser = CustomUser.objects.get(email=questions_list.author)
        email = questions_list.author
        login = customuser.login
        _answer, created = Answer.objects.get_or_create(question=questions_list, answer_text=answer_text, author=user)
        _answer.save()
        send_mail('Hasker. New answer', "Hello "
                  + login + " you have new answer for your question with title: "
                  + questions_list.title, settings.DEFAULT_FROM_EMAIL, [email])
    return redirect('questions:question_list')


def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    # Filter posts by tag name
    questions_list = Question.objects.filter(tags=tag)
    context = {
        'tag': tag,
        'questions_list': questions_list,
    }
    return render(request, 'questions/question_list.html', context)


def question_vote(request):
    user = request.user
    if request.method == "POST":
        question_id = request.POST.get('question_id')
        questions_list = Question.objects.get(id=question_id)
        if 'vote' in request.POST.keys():
            questions_list.voted.add(user)
        if 'unvote' in request.POST.keys():
            questions_list.voted.remove(user)
        vote, created = VoteQuestion.objects.get_or_create(user=user, question_id=question_id)
        if not created:
            if vote.polled == 'Poll':
                vote.polled = 'Unpoll'
            else:
                vote.polled = 'Poll'
        vote.save()
    return redirect('questions:question_list')


def answer_vote(request):
    user = request.user
    if request.method == "POST":
        answer_id = request.POST.get('answer_id')
        question_id = request.POST.get('question_id')
        answer_list = Answer.objects.get(id=answer_id)
        if 'answer_vote' in request.POST.keys():
            answer_list.voted.add(user)
        if 'answer_unvote' in request.POST.keys():
            answer_list.voted.remove(user)
        vote, created = VoteAnswer.objects.get_or_create(user=user, answer_id=answer_id)
        if not created:
            if vote.polled == 'Poll':
                vote.polled = 'Unpoll'
            else:
                vote.polled = 'Poll'
        vote.save()
    return redirect('questions:question_detail', question_id)


def answer_right(request):
    if request.method == "POST":
        answer_id = request.POST.get('answer_id')
        question_id = request.POST.get('question_id')
        right_flag = True if request.POST.get('right_flag') == 'on' else False
        answer = Answer.objects.get(id=answer_id)
        answer.right_flag = right_flag
        answer.save()
    return redirect('questions:question_detail', question_id)


class SearchResultsListView(ListView):
    model = Question
    context_object_name = 'question_list'
    template_name = 'questions/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        return Question.objects.filter(
            Q(title__icontains=query)
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        answers = Answer.objects.all()
        context['answers'] = answers
        return context

templates/_base.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">

    <title>{% block title %}Haskers{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="/static/css/tagsinput.css"/>

</head>
<body>
<header>
    {% if user.is_authenticated %}
        <div class="container-fluid bg-white border-bottom border-dark">
            <div class="row py-3">
                <div class="col">
                    <img src="https://cdn.freebiesupply.com/logos/large/2x/stackoverflow-com-logo-png-transparent.png"
                         alt="Home" style="width:38px;height:33px;"><a href="/"><h3>Haskers</h3></a>
                </div>
                <div class="d-flex">
                    <ul class="nav nav-fill align-items-center">
                        <li class="nav-item nav-link">
                            <form class="form-inline mt-2 mt-md-0" action="{% url 'search_results' %}" method="get">
                                {% csrf_token %}
                                <div class="input-group">
                                    <button class="btn btn-outline-primary" type="submit" name="q">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                             fill="currentColor"
                                             class="bi bi-search" viewBox="0 0 16 16">
                                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397
                                        1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1
                                        1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0
                                        0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z">
                                            </path>
                                        </svg>
                                    </button>
                                    <input name="q" type="text" class="form-control" placeholder="Search"
                                           aria-label="Search"
                                           aria-describedby="basic-addon1">

                                </div>
                            </form>
                        </li>
                        <li class="nav-item nav-link">
                            <a class="p-2 text-dark" href="{% url 'settings' %}">{{ user.login }}</a>
                            <br>
                            <a href="{% url 'account_logout' %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                                     class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd"
                                          d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0
                                          0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0
                                          0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5
                                          1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z"/>
                                    <path fill-rule="evenodd"
                                          d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1
                                          .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147
                                          2.146a.5.5 0 0 1-.708.708l-3-3z"/>
                                </svg>


                            </a>
                        </li>
                        <li class="nav-item nav-link">
                            <img class="bookcover" src="{{ user.avatar.url }}" alt="{{ user.login }}">
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    {% else %}
        <div class="container-fluid bg-white border-bottom border-dark">
            <div class="row py-2">
                <div class="col">
                    <img src="https://cdn.freebiesupply.com/logos/large/2x/stackoverflow-com-logo-png-transparent.png"
                         alt="Home" style="width:38px;height:33px;"><a href="/"><h3>Haskers</h3></a>
                </div>
                <div class="d-flex">
                    <ul class="nav nav-fill align-items-center">
                        <li class="nav-item nav-link">
                            <div class="input-group">
                            <span class="input-group-text" id="basic-addon1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-search" viewBox="0 0 16 16">
                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path>
                    </svg>
                </span><input type="text" class="form-control" placeholder="Search" aria-label="Search"
                              aria-describedby="basic-addon1"></div>
                        </li>
                        <li class="nav-item nav-link">
                            <a href="{% url 'account_login' %}" class="nav-link">Log In</a>
                        </li>
                        <li class="nav-item nav-link">
                            <a href="{% url 'account_signup' %}">
                                <button class="btn btn-primary btn-sm" type="button" style="height:40px; width:120px;">
                                    Sign Up
                                </button>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    {% endif %}
</header>
<div class="container-flex">
    <div class="row">
        <div class="col-md-8 my-2 mx-2">
            {% block content %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endblock content %}
        </div>
        <div class="col my-2 mx-2">
            <div class="card mb-3 w-100">
                <div class="card-body">
                    <p class="card-text">
                    <div class="d-grid gap-4">
                        <a class="btn btn-primary" style="height:40px; width:120px;"
                           href="{% url 'questions:create_question' %}">
                            Ask!
                        </a>
                    </div>
                    </p>
                    <hr>
                    <h4 class="card-text">
                        <span class="text-primary">Trending</span>
                    </h4>
                    {% for q in question_list %}
                        <p></p>
                        {% if q.voted.all.count > 0 %}
                            <button class="btn btn-primary">
                                <strong>{{ q.voted.all.count }}</strong>
                            </button>
                            <a href="">{{ q.title }}</a>
                        {% endif %}
                    {% endfor %}
                    <a>
                    </a>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- JavaScript -->
<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"
        integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="/static/js/tagsinput.js"></script>
<script>
    $("#question-form").submit(function (e) {
        e.preventDefault();
    });</script>
</body>
</html>

templates/answers.html
{% extends '_base.html' %}
{% block title %}Answers{% endblock title %}
{% block content %} <h1>Answers</h1>
{% endblock content %}

templates/questions.html
{% extends '_base.html' %}
{% block title %}Questions{% endblock title %}
{% block content %} <h1>Questions</h1>
{% endblock content %}